CREATE OR REPLACE PROCEDURE FIDE_AUTENTICAR_USUARIO_SP (
    P_NOMBRE IN FIDE_USUARIOS_TB.NOMBRE%TYPE,
    P_CONTRASENA IN FIDE_USUARIOS_TB.CONTRASENA%TYPE,
    P_USUARIO_ID OUT FIDE_USUARIOS_TB.ID_USUARIO%TYPE,
    P_EXISTE OUT NUMBER
) AS
BEGIN
    BEGIN
        SELECT ID_USUARIO INTO P_USUARIO_ID
        FROM FIDE_USUARIOS_TB
        WHERE NOMBRE = P_NOMBRE
        AND CONTRASENA = P_CONTRASENA
        AND ACTIVO = 1;
        
        P_EXISTE := 1; -- Usuario encontrado
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            P_USUARIO_ID := NULL;
            P_EXISTE := 0; -- Usuario no encontrado
        WHEN OTHERS THEN
            P_USUARIO_ID := NULL;
            P_EXISTE := -1; -- Error en la consulta
    END;
END; 