-- CREACION ENTIDADES
DROP TABLE FIDE_USUARIOS_TB;
CREATE TABLE FIDE_USUARIOS_TB (
    ID_USUARIO NUMBER
        CONSTRAINT FIDE_USUARIOS_ID_PK PRIMARY KEY,
    NOMBRE VARCHAR2(50)
        CONSTRAINT FIDE_USUARIOS_NOMBRE_NOT_NULL NOT NULL,
    PRIMER_APELLIDO VARCHAR2(50)
        CONSTRAINT FIDE_USUARIOS_PAPELLIDO_NOT_NULL NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(50)
        CONSTRAINT FIDE_USUARIOS_SAPELLIDO_NOT_NULL NOT NULL,
    CORREO VARCHAR2(100)
        CONSTRAINT FIDE_USUARIOS_CORREO_UNIQUE_IDX UNIQUE
        CONSTRAINT FIDE_USUARIOS_CORREO_NOT_NULL NOT NULL,
    CONTRASENA VARCHAR2(255)
        CONSTRAINT FIDE_USUARIOS_CONTRASENA_NOT_NULL NOT NULL,
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_USUARIOS_ACTIVO_NOT_NULL NOT NULL
);
/
DROP TABLE FIDE_ROL_TB;
CREATE TABLE FIDE_ROL_TB (
    ID_ROL NUMBER
        CONSTRAINT ROLES_ID_ROL_PK PRIMARY KEY,
    NOMBRE VARCHAR2(50)
        CONSTRAINT ROLES_NOMBRE_ROL_NOT_NULL NOT NULL,
    ACTIVO NUMBER(1,0)
        CONSTRAINT ROLES_ACTIVO_NOT_NULL NOT NULL
);
/
DROP TABLE FIDE_USUARIO_ROL_TB;
CREATE TABLE FIDE_USUARIO_ROL_TB (
    ID_ROL NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    CONSTRAINT FIDE_USUARIO_ROL_ID_ROL_FK
        FOREIGN KEY (ID_ROL)
        REFERENCES FIDE_ROL_TB(ID_ROL),
    CONSTRAINT FIDE_USUARIO_ROL_ID_USUARIO_FK
        FOREIGN KEY (ID_USUARIO)
        REFERENCES FIDE_USUARIOS_TB(ID_USUARIO),
    CONSTRAINT FIDE_USUARIO_ROL_PK
        PRIMARY KEY (ID_ROL, ID_USUARIO)
);
/
DROP TABLE FIDE_NOTIFICACIONES_TB;
CREATE TABLE FIDE_NOTIFICACIONES_TB (
    ID_NOTIFICACION NUMBER 
        CONSTRAINT FIDE_NOTIFICACIONES_ID_NOTIFICACION_PK PRIMARY KEY,
    MENSAJE VARCHAR2(1000),
    TIPO VARCHAR2(20),
    FECHA_ENVIO DATE,
    ACTIVO NUMBER(1,0) 
        CONSTRAINT FIDE_NOTIFICACIONES_ACTIVO_NOT_NULL NOT NULL,
    ID_USUARIO NUMBER
);
/
DROP TABLE FIDE_DOCTORES_TB;
CREATE TABLE FIDE_DOCTORES_TB (
    ID_DOCTOR NUMBER
        CONSTRAINT FIDE_DOCTORES_ID_DOCTOR_PK PRIMARY KEY,
    TELEFONO VARCHAR2(15),
    NUMEROLICENCIA VARCHAR2(50)
        CONSTRAINT FIDE_DOCTORES_NUMEROLICENCIA_UNIQUE UNIQUE
        CONSTRAINT FIDE_DOCTORES_NUMEROLICENCIA_NOT_NULL NOT NULL,
    ID_USUARIO NUMBER
        CONSTRAINT FIDE_DOCTORES_ID_USUARIO_NOT_NULL NOT NULL,
    ID_DIRECCION NUMBER
        CONSTRAINT FIDE_DOCTORES_ID_DIRECCION_NOT_NULL NOT NULL,
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_DOCTORES_ACTIVO_NOT_NULL NOT NULL
);
/
DROP TABLE FIDE_PACIENTES_TB;
CREATE TABLE FIDE_PACIENTES_TB (
    ID_PACIENTE NUMBER
        CONSTRAINT FIDE_PACIENTES_ID_PACIENTE_PK PRIMARY KEY,
    FECHA_NACIMIENTO DATE
        CONSTRAINT FIDE_PACIENTES_FECHA_NACIMIENTO_NOT_NULL NOT NULL,
    NUMERO_SEGURO VARCHAR2(50),
    DIRECCION VARCHAR2(255)
        CONSTRAINT FIDE_PACIENTES_DIRECCION_NOT_NULL NOT NULL,
    TELEFONO VARCHAR2(15)
        CONSTRAINT FIDE_PACIENTES_TELEFONO_NOT_NULL NOT NULL,
    ID_USUARIO NUMBER,
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_PACIENTES_ACTIVO_NOT_NULL NOT NULL,
    ID_DIRECCION NUMBER
        CONSTRAINT FIDE_PACIENTES_ID_DIRECCION_NOT_NULL NOT NULL
);
/
DROP TABLE FIDE_DIRECION_TB;
CREATE TABLE FIDE_DIRECCION_TB (
    ID_DIRECCION NUMBER
        CONSTRAINT FIDE_DIRECCION_ID_DIRECCION_PK PRIMARY KEY,
    PAIS VARCHAR2(30)
        CONSTRAINT FIDE_DIRECCION_PAIS_NOT_NULL NOT NULL,
    CANTON VARCHAR2(30)
        CONSTRAINT FIDE_DIRECCION_CANTON_NOT_NULL NOT NULL,
    DISTRITO VARCHAR2(30)
        CONSTRAINT FIDE_DIRECCION_DISTRITO_NOT_NULL NOT NULL,
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_DIRECCION_ACTIVO_NOT_NULL NOT NULL
);
DROP TABLE FIDE_DISPONIBILIDAD_TB;
CREATE TABLE FIDE_DISPONIBILIDAD_TB (
    ID_DISPONIBILIDAD NUMBER
        CONSTRAINT FIDE_DISPONIBILIDAD_ID_DISPONIBILIDAD_PK PRIMARY KEY,
    DIA VARCHAR2(30)
        CONSTRAINT FIDE_DISPONIBILIDAD_DIA_NN NOT NULL,
    HORA_INICIO DATE,
    HORA_FIN DATE,
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_DISPONIBILIDAD_ACTIVO_NN NOT NULL,
    ID_DOCTOR NUMBER
        CONSTRAINT FIDE_DISPONIBILIDAD_ID_DOCTOR_NN NOT NULL
);
/
DROP TABLE FIDE_ESPECIALIDADES_TB;
CREATE TABLE FIDE_ESPECIALIDADES_TB (
    ID_ESPECIALIDAD NUMBER
        CONSTRAINT FIDE_ESPECIALIDADES_ID_ESPECIALIDAD_PK PRIMARY KEY,
    NOMBRE VARCHAR2(50)
        CONSTRAINT FIDE_ESPECIALIDADES_NOMBRE_NN NOT NULL,
    DESCRIPCION VARCHAR2(2000),
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_ESPECIALIDADES_ACTIVO_NN NOT NULL
);

/
DROP TABLE FIDE_DOCTORES_ESPECIALIDADES_TB;
CREATE TABLE FIDE_DOCTORES_ESPECIALIDADES_TB (
    ID_ESPECIALIDAD NUMBER
        CONSTRAINT FIDE_DOCTORES_ESPECIALIDADES_ID_ESPECIALIDAD_NN NOT NULL,
    ID_DOCTOR NUMBER
        CONSTRAINT FIDE_DOCTORES_ESPECIALIDADES_ID_DOCTOR_NN NOT NULL,
    CONSTRAINT FIDE_DOCTORES_ESPECIALIDADES_PK
        PRIMARY KEY (ID_ESPECIALIDAD, ID_DOCTOR),
    CONSTRAINT FIDE_DOCTORES_ESPECIALIDADES_ID_ESPECIALIDAD_FK
        FOREIGN KEY (ID_ESPECIALIDAD)
        REFERENCES FIDE_ESPECIALIDADES_TB(ID_ESPECIALIDAD),
    CONSTRAINT FIDE_DOCTORES_ESPECIALIDADES_ID_DOCTOR_FK
        FOREIGN KEY (ID_DOCTOR)
        REFERENCES FIDE_DOCTORES_TB(ID_DOCTOR)
);
/DROP TABLE FIDE_SUBESPECIALIDAD_TB;
CREATE TABLE FIDE_SUBESPECIALIDAD_TB (
    ID_SUBESPECIALIDAD NUMBER
        CONSTRAINT FIDE_SUBESPECIALIDAD_ID_SUBESPECIALIDAD_PK PRIMARY KEY,
    NOMBRE VARCHAR2(50)
        CONSTRAINT FIDE_SUBESPECIALIDAD_NOMBRE_NN NOT NULL,
    DESCRIPCION VARCHAR2(2000),
    ID_ESPECIALIDAD NUMBER(6)
        CONSTRAINT FIDE_SUBESPECIALIDAD_ID_ESPECIALIDAD_NN NOT NULL,
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_SUBESPECIALIDAD_ACTIVO_NN NOT NULL
);
/
DROP TABLE FIDE_SERVICIO_TB;
CREATE TABLE FIDE_SERVICIO_TB (
    ID_SERVICIO NUMBER
        CONSTRAINT FIDE_SERVICIO_ID_SERVICIO_PK PRIMARY KEY,
    NOMBRE VARCHAR2(30)
        CONSTRAINT FIDE_SERVICIO_NOMBRE_NN NOT NULL,
    DESCRIPCION VARCHAR2(2000),
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_SERVICIO_ACTIVO_NN NOT NULL
);
/
CREATE TABLE FIDE_SERVICIO_ESPECIALIDAD_TB (
    ID_SERVICIO NUMBER
        CONSTRAINT FIDE_SERVICIO_ESPECIALIDAD_ID_SERVICIO_NN NOT NULL,
    ID_ESPECIALIDAD NUMBER
        CONSTRAINT FIDE_SERVICIO_ESPECIALIDAD_ID_ESPECIALIDAD_NN NOT NULL,
    CONSTRAINT FIDE_SERVICIO_ESPECIALIDAD_PK
        PRIMARY KEY (ID_SERVICIO, ID_ESPECIALIDAD),
    CONSTRAINT FIDE_SERVICIO_ESPECIALIDAD_ID_SERVICIO_FK
        FOREIGN KEY (ID_SERVICIO)
        REFERENCES FIDE_SERVICIO_TB(ID_SERVICIO),
    CONSTRAINT FIDE_SERVICIO_ESPECIALIDAD_ID_ESPECIALIDAD_FK
        FOREIGN KEY (ID_ESPECIALIDAD)
        REFERENCES FIDE_ESPECIALIDADES_TB(ID_ESPECIALIDAD)
);
DROP TABLE FIDE_PROCEDIMIENTOS_TB;
CREATE TABLE FIDE_PROCEDIMIENTOS_TB (
    ID_PROCEDIMIENTO NUMBER 
        CONSTRAINT FIDE_PROCEDIMIENTOS_PK PRIMARY KEY,
    NOMBRE_PROCEDIMIENTO VARCHAR2(50) 
        CONSTRAINT FIDE_PROCEDIMIENTOS_NOMBRE_NN NOT NULL,
    DESCRIPTION VARCHAR2(255) 
        CONSTRAINT FIDE_PROCEDIMIENTOS_DESC_NN NOT NULL,
    TIPO_PROCEDIMIENTO VARCHAR2(20) 
        CONSTRAINT FIDE_PROCEDIMIENTOS_TIPO_NN NOT NULL,
    RIESGO VARCHAR2(10),
    ACTIVO NUMBER(1,0) 
        CONSTRAINT FIDE_PROCEDIMIENTOS_ACTIVO_NN NOT NULL
);
/
DROP TABLE FIDE_TRATAMIENTOS_TB;
CREATE TABLE FIDE_TRATAMIENTOS_TB (
    ID_TRATAMIENTO NUMBER 
        CONSTRAINT FIDE_TRATAMIENTOS_PK PRIMARY KEY,
    DESCRIPCION VARCHAR2(2000),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ACTIVO NUMBER(1,0) 
        CONSTRAINT FIDE_TRATAMIENTOS_ACTIVO_NN NOT NULL,
    ID_PACIENTE NUMBER 
);
/
DROP TABLE FIDE_TRATAMIENTOS_PROCEDIMIENTOS_TB;
CREATE TABLE FIDE_TRATAMIENTOS_PROCEDIMIENTOS_TB (
    ID_TRATAMIENTO NUMBER NOT NULL,
    ID_PROCEDIMIENTO NUMBER NOT NULL,
    CONSTRAINT FIDE_TRATAMIENTOS_PROCEDIMIENTOS_PK PRIMARY KEY (ID_TRATAMIENTO, ID_PROCEDIMIENTO),
    CONSTRAINT FK_TP_TRATAMIENTO FOREIGN KEY (ID_TRATAMIENTO)
        REFERENCES FIDE_TRATAMIENTOS_TB(ID_TRATAMIENTO),
    CONSTRAINT FK_TP_PROCEDIMIENTO FOREIGN KEY (ID_PROCEDIMIENTO)
        REFERENCES FIDE_PROCEDIMIENTOS_TB(ID_PROCEDIMIENTO)
);

/
DROP TABLE FIDE_CITAS_TB;
CREATE TABLE FIDE_CITAS_TB (
    ID_CITA NUMBER
        CONSTRAINT FIDE_CITAS_TB_ID_CITA_PK PRIMARY KEY,
    FECHA DATE
        CONSTRAINT FIDE_CITAS_TB_FECHA_NOT_NULL NOT NULL,
    HORA_CITA VARCHAR2(10)
        CONSTRAINT FIDE_CITAS_TB_HORA_CITA_NOT_NULL NOT NULL,
    ID_ESTADO_CITA NUMBER
        CONSTRAINT FIDE_CITAS_TB_ID_ESTADO_CITA_NOT_NULL NOT NULL,
    ID_DOCTOR NUMBER
        CONSTRAINT FIDE_CITAS_TB_ID_DOCTOR_NOT_NULL NOT NULL,
    ID_PACIENTE NUMBER
        CONSTRAINT FIDE_CITAS_TB_ID_PACIENTE_NOT_NULL NOT NULL,
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_CITAS_TB_ACTIVO_NOT_NULL NOT NULL
);
/
DROP TABLE FIDE_CITAS_TRATAMIENTOS_TB;
CREATE TABLE FIDE_CITAS_TRATAMIENTOS_TB (
    ID_CITA NUMBER NOT NULL,
    ID_TRATAMIENTO NUMBER NOT NULL,
    CONSTRAINT FIDE_CITAS_TRATAMIENTOS_PK
        PRIMARY KEY (ID_CITA, ID_TRATAMIENTO),
    CONSTRAINT FIDE_CITAS_TRATAMIENTOS_ID_CITA_FK
        FOREIGN KEY (ID_CITA)
        REFERENCES FIDE_CITAS_TB(ID_CITA),
    CONSTRAINT FIDE_CITAS_TRATAMIENTOS_ID_TRATAMIENTO_FK
        FOREIGN KEY (ID_TRATAMIENTO)
        REFERENCES FIDE_TRATAMIENTOS_TB(ID_TRATAMIENTO)
);
/
DROP TABLE FIDE_CITAS_PROCEDIMIENTOS_TB;
CREATE TABLE FIDE_CITAS_PROCEDIMIENTOS_TB (
    ID_CITA NUMBER NOT NULL,
    ID_PROCEDIMIENTO NUMBER NOT NULL,
    CONSTRAINT FIDE_CITAS_PROCEDIMIENTOS_PK
        PRIMARY KEY (ID_CITA, ID_PROCEDIMIENTO),
    CONSTRAINT FIDE_CITAS_PROCEDIMIENTOS_ID_CITA_FK
        FOREIGN KEY (ID_CITA)
        REFERENCES FIDE_CITAS_TB(ID_CITA),
    CONSTRAINT FIDE_CITAS_PROCEDIMIENTOS_ID_PROCEDIMIENTO_FK
        FOREIGN KEY (ID_PROCEDIMIENTO)
        REFERENCES FIDE_PROCEDIMIENTOS_TB(ID_PROCEDIMIENTO)
);
/
CREATE TABLE FIDE_ESTADOS_CITA_TB (
    ID_ESTADO NUMBER
        CONSTRAINT FIDE_ESTADOS_CITA_TB_ID_ESTADO_PK PRIMARY KEY,
    NOMBRE_ESTADO VARCHAR2(10)
        CONSTRAINT FIDE_ESTADOS_CITA_TB_NOMBRE_ESTADO_NOT_NULL NOT NULL,
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_ESTADOS_CITA_TB_ACTIVO_NOT_NULL NOT NULL
);
CREATE TABLE FIDE_COSTOS_CITA_TB (
    ID_COSTO NUMBER 
        CONSTRAINT FIDE_COSTOS_CITA_ID_COSTO_PK PRIMARY KEY,
    ID_CITA NUMBER 
        CONSTRAINT FIDE_COSTOS_CITA_ID_CITA_FK REFERENCES FIDE_CITAS_TB(ID_CITA),
    MONTO NUMBER(10,2) 
        CONSTRAINT FIDE_COSTOS_CITA_MONTO_NOT_NULL NOT NULL,
    DESCRIPCION VARCHAR2(2000),
    ACTIVO NUMBER(1,0) 
        CONSTRAINT FIDE_COSTOS_CITA_TB_ACTIVO_NOT_NULL NOT NULL
);
/
DROP TABLE FIDE_HISTORIAL_CITAS_TB;
CREATE TABLE FIDE_HISTORIAL_CITAS_TB (
    ID_HISTORIAL NUMBER NOT NULL,
    ID_CITA NUMBER NOT NULL,
    FECHA_CAMBIO DATE,
    ID_ESTADO_ANTERIOR NUMBER,
    ID_ESTADO_NUEVO NUMBER,
    OBSERVACIONES VARCHAR2(500),
    ACTIVO NUMBER(1,0) NOT NULL,
    CONSTRAINT FIDE_HISTORIAL_CITAS_ID_HISTORIAL_PK PRIMARY KEY (ID_HISTORIAL)
);

CREATE TABLE FIDE_MEDICAMENTOS_TB (
    ID_MEDICAMENTO NUMBER
        CONSTRAINT FIDE_MEDICAMENTOS_ID_MEDICAMENTO_PK PRIMARY KEY,
    NOMBRE VARCHAR2(50)
        CONSTRAINT FIDE_MEDICAMENTOS_NOMBRE_NN NOT NULL,
    DESCRIPCION VARCHAR2(2000),
    PRECIO NUMBER(10,2),
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_MEDICAMENTOS_ACTIVO_NN NOT NULL
);
/
DROP TABLE FIDE_INVENTARIO_MEDICAMENTOS_TB;
CREATE TABLE FIDE_INVENTARIO_MEDICAMENTOS_TB (
    ID_INVENTARIO NUMBER
        CONSTRAINT FIDE_INVENTARIO_MEDICAMENTOS_ID_INVENTARIO_PK PRIMARY KEY,
    ID_MEDICAMENTO NUMBER
        CONSTRAINT FIDE_INVENTARIO_MEDICAMENTOS_ID_MEDICAMENTO_NN NOT NULL,
    CANTIDAD NUMBER
        CONSTRAINT FIDE_INVENTARIO_MEDICAMENTOS_CANTIDAD_NN NOT NULL,
    FECHA_ULTIMA_ACTUALIZACION DATE,
    OBSERVACIONES VARCHAR2(1000)
);
/
DROP TABLE FIDE_FACTURAS_TB;

CREATE TABLE FIDE_FACTURAS_TB (
    ID_FACTURA NUMBER
        CONSTRAINT FIDE_FACTURAS_ID_FACTURA_PK PRIMARY KEY,
    NUMERO_FACTURA VARCHAR2(50)
        CONSTRAINT FIDE_FACTURAS_NUMERO_FACTURA_NN NOT NULL,
    FECHA_EMISION DATE
        CONSTRAINT FIDE_FACTURAS_FECHA_EMISION_NN NOT NULL,
    FECHA_VENCIMIENTO DATE,
    MONTO_TOTAL NUMBER(10,2)
        CONSTRAINT FIDE_FACTURAS_MONTO_TOTAL_NN NOT NULL,
    ESTADO_PAGO VARCHAR2(20)
        CONSTRAINT FIDE_FACTURAS_ESTADO_NN NOT NULL,
    ID_PACIENTE NUMBER
        CONSTRAINT FIDE_FACTURAS_ID_PACIENTE_FK
        REFERENCES FIDE_PACIENTES_TB(ID_PACIENTE),
    ACTIVO NUMBER(1,0)
);

DROP TABLE FIDE_FACTURAS_DETALLE_TB;
CREATE TABLE FIDE_FACTURAS_DETALLE_TB (
    ID_FACTURA NUMBER NOT NULL,
    ID_COSTO NUMBER NOT NULL,
    MONTO NUMBER(10,2)
        CONSTRAINT FIDE_FACTURAS_DETALLE_MONTO_NN NOT NULL,
    DESCRIPCION VARCHAR2(2000),
    CONSTRAINT FIDE_FACTURAS_DETALLE_PK
        PRIMARY KEY (ID_FACTURA, ID_COSTO)
)






