--RELACIONES ENTIDADES

-- Relacion Usuarios 1:N Notificaciones  
ALTER TABLE FIDE_NOTIFICACIONES_TB
ADD CONSTRAINT FK_NOTIFICACIONES_USUARIO
FOREIGN KEY (ID_USUARIO)
REFERENCES FIDE_USUARIOS_TB(ID_USUARIO);

-- Relacion Pacientes 1:1 Usuarios
ALTER TABLE FIDE_PACIENTES_TB
ADD CONSTRAINT FIDE_PACIENTES_ID_USUARIO_FK
    FOREIGN KEY (ID_USUARIO)
    REFERENCES FIDE_USUARIOS_TB(ID_USUARIO);

--Relacion Doctores 1:1 Usuarios
ALTER TABLE FIDE_DOCTORES_TB
ADD CONSTRAINT FIDE_DOCTORES_ID_USUARIO_FK
    FOREIGN KEY (ID_USUARIO)
    REFERENCES FIDE_USUARIOS_TB(ID_USUARIO);
	
--Relacion Pacientes 1:N Direccion
ALTER TABLE FIDE_PACIENTES_TB
ADD CONSTRAINT FIDE_PACIENTES_ID_DIRECCION_FK
    FOREIGN KEY (ID_DIRECCION)
    REFERENCES FIDE_DIRECCION_TB(ID_DIRECCION);
    
--Relacion Doctores 1:N Direccion
ALTER TABLE FIDE_DOCTORES_TB
ADD CONSTRAINT FIDE_DOCTORES_ID_DIRECCION_FK
    FOREIGN KEY (ID_DIRECCION)
    REFERENCES FIDE_DIRECCION_TB(ID_DIRECCION);
    
--Relacion Disponibilidad N:1 Doctores
ALTER TABLE FIDE_DISPONIBILIDAD_TB
ADD CONSTRAINT FIDE_DISPONIBILIDAD_ID_DOCTOR_FK
    FOREIGN KEY (ID_DOCTOR)
    REFERENCES FIDE_DOCTORES_TB(ID_DOCTOR);
    
--Relacion SubEspecialidad N:1 Especialidad
ALTER TABLE FIDE_SUBESPECIALIDAD_TB
ADD CONSTRAINT FIDE_SUBESPECIALIDAD_ID_ESPECIALIDAD_FK
    FOREIGN KEY (ID_ESPECIALIDAD)
    REFERENCES FIDE_ESPECIALIDADES_TB(ID_ESPECIALIDAD);


