
-- SQL FILE - CREACION ENTIDADES

DROP TABLE FIDE_USUARIOS_TB;
CREATE TABLE FIDE_USUARIOS_TB (
    ID_USUARIO NUMBER 
        CONSTRAINT FIDE_USUARIOS_ID_USUARIO_PK PRIMARY KEY,
    NOMBRE VARCHAR2(50) 
        CONSTRAINT USUARIOS_NOMBRE_NOT_NULL NOT NULL,
    PRIMER_APELLIDO VARCHAR2(50)
        CONSTRAINT USUARIOS_PRIMER_APELLIDO_NOT_NULL NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(50)
        CONSTRAINT USUARIOS_SEGUNDO_APELLIDO_NOT_NULL NOT NULL,
    CORREO VARCHAR2(100)
        CONSTRAINT USUARIOS_CORREO_NOT_NULL NOT NULL,
    CONTRASENA VARCHAR2(255)
        CONSTRAINT USUARIOS_CONTRASENA_NOT_NULL NOT NULL,
    ACTIVO NUMBER(1,0)
        CONSTRAINT USUARIOS_ACTIVO_NOT_NULL NOT NULL,
    ID_ROL NUMBER
        CONSTRAINT USUARIOS_ID_ROL_NOT_NULL NOT NULL
);

COMMIT
/
CREATE TABLE ROLES_TB (
    ID_ROL NUMBER
        CONSTRAINT ROLES_ID_ROL_PK PRIMARY KEY,
    NOMBRE_ROL VARCHAR2(50)
        CONSTRAINT ROLES_NOMBRE_ROL_NOT_NULL NOT NULL,
    ACTIVO NUMBER(1,0)
        CONSTRAINT ROLES_ACTIVO_NOT_NULL NOT NULL
);
COMMIT
/
CREATE TABLE Pacientes (
    id_asciente NUMBER NOT NULL PRIMARY KEY,
    fecha_pacimiento DATE NOT NULL,
    numero_seguro VARCHAR2(50),
    direccion VARCHAR2(255) NOT NULL,
    telefono VARCHAR2(15) NOT NULL,
    id_usuario NUMBER,
    activo NUMBER(1,0) NOT NULL,
    id_direccion NUMBER NOT NULL,
);

CREATE TABLE Notificaciones (
    id_notificacion NUMBER NOT NULL PRIMARY KEY,
    mensaje VARCHAR2(1000),
    tipo VARCHAR2(20),
    fecha_envio DATE,
    activo NUMBER(1,0) NOT NULL,
    id_usuarios NUMBER,
);

CREATE TABLE Historial_tratamientos (
    id_basicinte NUMBER NOT NULL PRIMARY KEY,
    fecha_inico DATE,
    fecha_fin DATE,
    observaciones VARCHAR2(255),
    activo NUMBER(1,0) NOT NULL
);




