-- CREACION ENTIDADES
DROP TABLE FIDE_USUARIOS_TB;
CREATE TABLE FIDE_USUARIOS_TB (
    ID_USUARIO NUMBER
        CONSTRAINT FIDE_USUARIOS_ID_PK PRIMARY KEY,
    NOMBRE VARCHAR2(50)
        CONSTRAINT FIDE_USUARIOS_NOMBRE_NOT_NULL NOT NULL,
    PRIMER_APELLIDO VARCHAR2(50)
        CONSTRAINT FIDE_USUARIOS_PAPELLIDO_NOT_NULL NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(50)
        CONSTRAINT FIDE_USUARIOS_SAPELLIDO_NOT_NULL NOT NULL,
    CORREO VARCHAR2(100)
        CONSTRAINT FIDE_USUARIOS_CORREO_UNIQUE_IDX UNIQUE
        CONSTRAINT FIDE_USUARIOS_CORREO_NOT_NULL NOT NULL,
    CONTRASENA VARCHAR2(255)
        CONSTRAINT FIDE_USUARIOS_CONTRASENA_NOT_NULL NOT NULL,
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_USUARIOS_ACTIVO_NOT_NULL NOT NULL
);
/
DROP TABLE FIDE_ROL_TB;
CREATE TABLE FIDE_ROL_TB (
    ID_ROL NUMBER
        CONSTRAINT ROLES_ID_ROL_PK PRIMARY KEY,
    NOMBRE VARCHAR2(50)
        CONSTRAINT ROLES_NOMBRE_ROL_NOT_NULL NOT NULL,
    ACTIVO NUMBER(1,0)
        CONSTRAINT ROLES_ACTIVO_NOT_NULL NOT NULL
);
/
DROP TABLE FIDE_USUARIO_ROL_TB;
CREATE TABLE FIDE_USUARIO_ROL_TB (
    ID_ROL NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    CONSTRAINT FIDE_USUARIO_ROL_ID_ROL_FK
        FOREIGN KEY (ID_ROL)
        REFERENCES FIDE_ROL_TB(ID_ROL),
    CONSTRAINT FIDE_USUARIO_ROL_ID_USUARIO_FK
        FOREIGN KEY (ID_USUARIO)
        REFERENCES FIDE_USUARIOS_TB(ID_USUARIO),
    CONSTRAINT FIDE_USUARIO_ROL_PK
        PRIMARY KEY (ID_ROL, ID_USUARIO)
);
/
DROP TABLE FIDE_NOTIFICACIONES_TB;
CREATE TABLE FIDE_NOTIFICACIONES_TB (
    ID_NOTIFICACION NUMBER 
        CONSTRAINT FIDE_NOTIFICACIONES_ID_NOTIFICACION_PK PRIMARY KEY,
    MENSAJE VARCHAR2(1000),
    TIPO VARCHAR2(20),
    FECHA_ENVIO DATE,
    ACTIVO NUMBER(1,0) 
        CONSTRAINT FIDE_NOTIFICACIONES_ACTIVO_NOT_NULL NOT NULL,
    ID_USUARIO NUMBER
);
/
DROP TABLE FIDE_DOCTORES_TB;
CREATE TABLE FIDE_DOCTORES_TB (
    ID_DOCTOR NUMBER
        CONSTRAINT FIDE_DOCTORES_ID_DOCTOR_PK PRIMARY KEY,
    TELEFONO VARCHAR2(15),
    NUMEROLICENCIA VARCHAR2(50)
        CONSTRAINT FIDE_DOCTORES_NUMEROLICENCIA_UNIQUE UNIQUE
        CONSTRAINT FIDE_DOCTORES_NUMEROLICENCIA_NOT_NULL NOT NULL,
    ID_USUARIO NUMBER
        CONSTRAINT FIDE_DOCTORES_ID_USUARIO_NOT_NULL NOT NULL,
    ID_DIRECCION NUMBER
        CONSTRAINT FIDE_DOCTORES_ID_DIRECCION_NOT_NULL NOT NULL,
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_DOCTORES_ACTIVO_NOT_NULL NOT NULL
);
/
DROP TABLE FIDE_PACIENTES_TB;
CREATE TABLE FIDE_PACIENTES_TB (
    ID_PACIENTE NUMBER
        CONSTRAINT FIDE_PACIENTES_ID_PACIENTE_PK PRIMARY KEY,
    FECHA_NACIMIENTO DATE
        CONSTRAINT FIDE_PACIENTES_FECHA_NACIMIENTO_NOT_NULL NOT NULL,
    NUMERO_SEGURO VARCHAR2(50),
    DIRECCION VARCHAR2(255)
        CONSTRAINT FIDE_PACIENTES_DIRECCION_NOT_NULL NOT NULL,
    TELEFONO VARCHAR2(15)
        CONSTRAINT FIDE_PACIENTES_TELEFONO_NOT_NULL NOT NULL,
    ID_USUARIO NUMBER,
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_PACIENTES_ACTIVO_NOT_NULL NOT NULL,
    ID_DIRECCION NUMBER
        CONSTRAINT FIDE_PACIENTES_ID_DIRECCION_NOT_NULL NOT NULL
);
/
DROP TABLE FIDE_DIRECION_TB;
CREATE TABLE FIDE_DIRECCION_TB (
    ID_DIRECCION NUMBER
        CONSTRAINT FIDE_DIRECCION_ID_DIRECCION_PK PRIMARY KEY,
    PAIS VARCHAR2(30)
        CONSTRAINT FIDE_DIRECCION_PAIS_NOT_NULL NOT NULL,
    CANTON VARCHAR2(30)
        CONSTRAINT FIDE_DIRECCION_CANTON_NOT_NULL NOT NULL,
    DISTRITO VARCHAR2(30)
        CONSTRAINT FIDE_DIRECCION_DISTRITO_NOT_NULL NOT NULL,
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_DIRECCION_ACTIVO_NOT_NULL NOT NULL
);
DROP TABLE FIDE_DISPONIBILIDAD_TB;
CREATE TABLE FIDE_DISPONIBILIDAD_TB (
    ID_DISPONIBILIDAD NUMBER
        CONSTRAINT FIDE_DISPONIBILIDAD_ID_DISPONIBILIDAD_PK PRIMARY KEY,
    DIA VARCHAR2(30)
        CONSTRAINT FIDE_DISPONIBILIDAD_DIA_NN NOT NULL,
    HORA_INICIO DATE,
    HORA_FIN DATE,
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_DISPONIBILIDAD_ACTIVO_NN NOT NULL,
    ID_DOCTOR NUMBER
        CONSTRAINT FIDE_DISPONIBILIDAD_ID_DOCTOR_NN NOT NULL
);
/
DROP TABLE FIDE_ESPECIALIDADES_TB;
CREATE TABLE FIDE_ESPECIALIDADES_TB (
    ID_ESPECIALIDAD NUMBER
        CONSTRAINT FIDE_ESPECIALIDADES_ID_ESPECIALIDAD_PK PRIMARY KEY,
    NOMBRE VARCHAR2(50)
        CONSTRAINT FIDE_ESPECIALIDADES_NOMBRE_NN NOT NULL,
    DESCRIPCION VARCHAR2(2000),
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_ESPECIALIDADES_ACTIVO_NN NOT NULL
);

/
DROP TABLE FIDE_DOCTORES_ESPECIALIDADES_TB;
CREATE TABLE FIDE_DOCTORES_ESPECIALIDADES_TB (
    ID_ESPECIALIDAD NUMBER
        CONSTRAINT FIDE_DOCTORES_ESPECIALIDADES_ID_ESPECIALIDAD_NN NOT NULL,
    ID_DOCTOR NUMBER
        CONSTRAINT FIDE_DOCTORES_ESPECIALIDADES_ID_DOCTOR_NN NOT NULL,
    CONSTRAINT FIDE_DOCTORES_ESPECIALIDADES_PK
        PRIMARY KEY (ID_ESPECIALIDAD, ID_DOCTOR),
    CONSTRAINT FIDE_DOCTORES_ESPECIALIDADES_ID_ESPECIALIDAD_FK
        FOREIGN KEY (ID_ESPECIALIDAD)
        REFERENCES FIDE_ESPECIALIDADES_TB(ID_ESPECIALIDAD),
    CONSTRAINT FIDE_DOCTORES_ESPECIALIDADES_ID_DOCTOR_FK
        FOREIGN KEY (ID_DOCTOR)
        REFERENCES FIDE_DOCTORES_TB(ID_DOCTOR)
);
/DROP TABLE FIDE_SUBESPECIALIDAD_TB;
CREATE TABLE FIDE_SUBESPECIALIDAD_TB (
    ID_SUBESPECIALIDAD NUMBER
        CONSTRAINT FIDE_SUBESPECIALIDAD_ID_SUBESPECIALIDAD_PK PRIMARY KEY,
    NOMBRE VARCHAR2(50)
        CONSTRAINT FIDE_SUBESPECIALIDAD_NOMBRE_NN NOT NULL,
    DESCRIPCION VARCHAR2(2000),
    ID_ESPECIALIDAD NUMBER(6)
        CONSTRAINT FIDE_SUBESPECIALIDAD_ID_ESPECIALIDAD_NN NOT NULL,
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_SUBESPECIALIDAD_ACTIVO_NN NOT NULL
);
/
DROP TABLE FIDE_SERVICIO_TB;
CREATE TABLE FIDE_SERVICIO_TB (
    ID_SERVICIO NUMBER
        CONSTRAINT FIDE_SERVICIO_ID_SERVICIO_PK PRIMARY KEY,
    NOMBRE VARCHAR2(30)
        CONSTRAINT FIDE_SERVICIO_NOMBRE_NN NOT NULL,
    DESCRIPCION VARCHAR2(2000),
    ACTIVO NUMBER(1,0)
        CONSTRAINT FIDE_SERVICIO_ACTIVO_NN NOT NULL
);
/
CREATE TABLE FIDE_SERVICIO_ESPECIALIDAD_TB (
    ID_SERVICIO NUMBER
        CONSTRAINT FIDE_SERVICIO_ESPECIALIDAD_ID_SERVICIO_NN NOT NULL,
    ID_ESPECIALIDAD NUMBER
        CONSTRAINT FIDE_SERVICIO_ESPECIALIDAD_ID_ESPECIALIDAD_NN NOT NULL,
    CONSTRAINT FIDE_SERVICIO_ESPECIALIDAD_PK
        PRIMARY KEY (ID_SERVICIO, ID_ESPECIALIDAD),
    CONSTRAINT FIDE_SERVICIO_ESPECIALIDAD_ID_SERVICIO_FK
        FOREIGN KEY (ID_SERVICIO)
        REFERENCES FIDE_SERVICIO_TB(ID_SERVICIO),
    CONSTRAINT FIDE_SERVICIO_ESPECIALIDAD_ID_ESPECIALIDAD_FK
        FOREIGN KEY (ID_ESPECIALIDAD)
        REFERENCES FIDE_ESPECIALIDADES_TB(ID_ESPECIALIDAD)
);







