--RELACIONES ENTIDADES

-- Relacion Usuarios 1:N Notificaciones  
ALTER TABLE FIDE_NOTIFICACIONES_TB
ADD CONSTRAINT FK_NOTIFICACIONES_USUARIO
FOREIGN KEY (ID_USUARIO)
REFERENCES FIDE_USUARIOS_TB(ID_USUARIO);

-- Relacion Pacientes 1:1 Usuarios
ALTER TABLE FIDE_PACIENTES_TB
ADD CONSTRAINT FIDE_PACIENTES_ID_USUARIO_FK
    FOREIGN KEY (ID_USUARIO)
    REFERENCES FIDE_USUARIOS_TB(ID_USUARIO);

--Relacion Doctores 1:1 Usuarios
ALTER TABLE FIDE_DOCTORES_TB
ADD CONSTRAINT FIDE_DOCTORES_ID_USUARIO_FK
    FOREIGN KEY (ID_USUARIO)
    REFERENCES FIDE_USUARIOS_TB(ID_USUARIO);
	
--Relacion Pacientes 1:N Direccion
ALTER TABLE FIDE_PACIENTES_TB
ADD CONSTRAINT FIDE_PACIENTES_ID_DIRECCION_FK
    FOREIGN KEY (ID_DIRECCION)
    REFERENCES FIDE_DIRECCION_TB(ID_DIRECCION);
    
--Relacion Doctores 1:N Direccion
ALTER TABLE FIDE_DOCTORES_TB
ADD CONSTRAINT FIDE_DOCTORES_ID_DIRECCION_FK
    FOREIGN KEY (ID_DIRECCION)
    REFERENCES FIDE_DIRECCION_TB(ID_DIRECCION);
    
--Relacion Disponibilidad N:1 Doctores
ALTER TABLE FIDE_DISPONIBILIDAD_TB
ADD CONSTRAINT FIDE_DISPONIBILIDAD_ID_DOCTOR_FK
    FOREIGN KEY (ID_DOCTOR)
    REFERENCES FIDE_DOCTORES_TB(ID_DOCTOR);
    
--Relacion SubEspecialidad N:1 Especialidad
ALTER TABLE FIDE_SUBESPECIALIDAD_TB
ADD CONSTRAINT FIDE_SUBESPECIALIDAD_ID_ESPECIALIDAD_FK
    FOREIGN KEY (ID_ESPECIALIDAD)
    REFERENCES FIDE_ESPECIALIDADES_TB(ID_ESPECIALIDAD);

--Relacion Tratamientos n:1 pacientes
ALTER TABLE FIDE_TRATAMIENTOS_TB
ADD CONSTRAINT FIDE_TRATAMIENTOS_TB_ID_PACIENTE_FK
FOREIGN KEY (ID_PACIENTE) 
REFERENCES FIDE_PACIENTES_TB(ID_PACIENTE);

ALTER TABLE FIDE_CITAS_TB
ADD CONSTRAINT FIDE_CITAS_TB_DOCTOR_FK
FOREIGN KEY (ID_DOCTOR)
REFERENCES FIDE_DOCTORES_TB(ID_DOCTOR);

ALTER TABLE FIDE_CITAS_TB
ADD CONSTRAINT FIDE_CITAS_TB_PACIENTE_FK
FOREIGN KEY (ID_PACIENTE)
REFERENCES FIDE_PACIENTES_TB(ID_PACIENTE);

ALTER TABLE FIDE_CITAS_TB
ADD CONSTRAINT FIDE_CITAS_TB_ESTADO_FK
FOREIGN KEY (ID_ESTADO_CITA)
REFERENCES FIDE_ESTADOS_CITA_TB(ID_ESTADO);

ALTER TABLE FIDE_HISTORIAL_CITAS_TB
ADD CONSTRAINT FIDE_HISTORIAL_CITAS_ID_CITA_FK
FOREIGN KEY (ID_CITA)
REFERENCES FIDE_CITAS_TB(ID_CITA);

-- FK hacia la tabla de EstadosCita (para el estado anterior)
ALTER TABLE FIDE_HISTORIAL_CITAS_TB
ADD CONSTRAINT FIDE_HISTORIAL_CITAS_ID_ESTADO_ANTERIOR_FK
FOREIGN KEY (ID_ESTADO_ANTERIOR)
REFERENCES FIDE_ESTADOS_CITA_TB(ID_ESTADO);

-- FK hacia la tabla de EstadosCita (para el estado nuevo)
ALTER TABLE FIDE_HISTORIAL_CITAS_TB
ADD CONSTRAINT FIDE_HISTORIAL_CITAS_ID_ESTADO_NUEVO_FK
FOREIGN KEY (ID_ESTADO_NUEVO)
REFERENCES FIDE_ESTADOS_CITA_TB(ID_ESTADO);


ALTER TABLE FIDE_INVENTARIO_MEDICAMENTOS_TB
ADD CONSTRAINT FIDE_INVENTARIO_MEDICAMENTOS_ID_MEDICAMENTO_FK
FOREIGN KEY (ID_MEDICAMENTO)
REFERENCES FIDE_MEDICAMENTOS_TB(ID_MEDICAMENTO);

COMMIT