--FIDE_USUARIOS_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_USUARIOS_SP(
    LISTA_USUARIOS OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_USUARIOS FOR
      SELECT ID_USUARIO, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO, CONTRASENA, 
             CREATION_DATE, CREATED_BY, LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_USUARIOS_TB;
END;
/

--FIDE_ROL_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_ROLES_SP(
    LISTA_ROLES OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_ROLES FOR
      SELECT ID_ROL, NOMBRE, CREATION_DATE, CREATED_BY, 
             LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_ROL_TB;
END;
/

--FIDE_USUARIO_ROL_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_USUARIO_ROLES_SP(
    LISTA_USUARIO_ROLES OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_USUARIO_ROLES FOR
      SELECT ID_ROL, ID_USUARIO
      FROM FIDE_USUARIO_ROL_TB;
END;
/

--FIDE_NOTIFICACIONES_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_NOTIFICACIONES_SP(
    LISTA_NOTIFICACIONES OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_NOTIFICACIONES FOR
      SELECT ID_NOTIFICACION, MENSAJE, TIPO, FECHA_ENVIO, ID_USUARIO,
             CREATION_DATE, CREATED_BY, LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_NOTIFICACIONES_TB;
END;
/

--FIDE_DOCTORES_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_DOCTORES_SP(
    LISTA_DOCTORES OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_DOCTORES FOR
      SELECT ID_DOCTOR, TELEFONO, NUMEROL_ICENCIA, ID_USUARIO, ID_DIRECCION,
             CREATION_DATE, CREATED_BY, LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_DOCTORES_TB;
END;
/



--FIDE_PACIENTES_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_PACIENTES_SP(
    LISTA_PACIENTES OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_PACIENTES FOR
      SELECT ID_PACIENTE, FECHA_NACIMIENTO, NUMERO_SEGURO, DIRECCION, TELEFONO,
             ID_USUARIO, ID_DIRECCION, CREATION_DATE, CREATED_BY, LAST_UPDATE, 
             LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_PACIENTES_TB;
END;
/


--FIDE_PAISES_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_PAISES_SP(
    LISTA_PAISES OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_PAISES FOR
      SELECT ID_PAIS, NOMBRE, CREATION_DATE, CREATED_BY,
             LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_PAISES_TB;
END;
/


--FIDE_CANTONES_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_CANTONES_SP(
    LISTA_CANTONES OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_CANTONES FOR
      SELECT ID_CANTON, NOMBRE, ID_PAIS, CREATION_DATE, CREATED_BY,
             LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_CANTONES_TB;
END;
/

--FIDE_DISTRITOS_TB


CREATE OR REPLACE PROCEDURE FIDE_LISTAR_DISTRITOS_SP(
    LISTA_DISTRITOS OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_DISTRITOS FOR
      SELECT ID_DISTRITO, NOMBRE, ID_CANTON, CREATION_DATE, CREATED_BY,
             LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_DISTRITOS_TB;
END;
/


--FIDE_DIRECCION_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_DIRECCIONES_SP(
    LISTA_DIRECCIONES OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_DIRECCIONES FOR
      SELECT ID_DIRECCION, ID_PAIS, ID_CANTON, ID_DISTRITO,
             CREATION_DATE, CREATED_BY, LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_DIRECCION_TB;
END;
/

--FIDE_DISPONIBILIDAD_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_DISPONIBILIDAD_SP(
    LISTA_DISPONIBILIDAD OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_DISPONIBILIDAD FOR
      SELECT ID_DISPONIBILIDAD, DIA, HORA_INICIO, HORA_FIN, ID_DOCTOR,
             CREATION_DATE, CREATED_BY, LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_DISPONIBILIDAD_TB;
END;
/

--FIDE_ESPECIALIDADES_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_ESPECIALIDADES_SP(
    LISTA_ESPECIALIDADES OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_ESPECIALIDADES FOR
      SELECT ID_ESPECIALIDAD, NOMBRE, DESCRIPCION, CREATION_DATE, CREATED_BY,
             LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_ESPECIALIDADES_TB;
END;
/

--FIDE_DOCTORES_ESPECIALIDADES_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_DOC_ESPECIALIDADES_SP(
    LISTA_DOC_ESPECIALIDADES OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_DOC_ESPECIALIDADES FOR
      SELECT ID_ESPECIALIDAD, ID_DOCTOR
      FROM FIDE_DOCTORES_ESPECIALIDADES_TB;
END;
/

--FIDE_SUBESPECIALIDAD_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_SUBESPECIALIDADES_SP(
    LISTA_SUBESPECIALIDADES OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_SUBESPECIALIDADES FOR
      SELECT ID_SUBESPECIALIDAD, NOMBRE, DESCRIPCION, ID_ESPECIALIDAD,
             CREATION_DATE, CREATED_BY, LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_SUBESPECIALIDAD_TB;
END;
/

--FIDE_SERVICIO_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_SERVICIOS_SP(
    LISTA_SERVICIOS OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_SERVICIOS FOR
      SELECT ID_SERVICIO, NOMBRE, DESCRIPCION, CREATION_DATE, CREATED_BY,
             LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_SERVICIO_TB;
END;
/

--FIDE_SERVICIO_ESPECIALIDAD_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_SERV_ESPECIALIDADES_SP(
    LISTA_SERV_ESPECIALIDADES OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_SERV_ESPECIALIDADES FOR
      SELECT ID_SERVICIO, ID_ESPECIALIDAD
      FROM FIDE_SERVICIO_ESPECIALIDAD_TB;
END;
/

--FIDE_PROCEDIMIENTOS_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_PROCEDIMIENTOS_SP(
    LISTA_PROCEDIMIENTOS OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_PROCEDIMIENTOS FOR
      SELECT ID_PROCEDIMIENTO, NOMBRE_PROCEDIMIENTO, DESCRIPTION, TIPO_PROCEDIMIENTO, RIESGO,
             CREATION_DATE, CREATED_BY, LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_PROCEDIMIENTOS_TB;
END;
/

--FIDE_TRATAMIENTOS_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_TRATAMIENTOS_SP(
    LISTA_TRATAMIENTOS OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_TRATAMIENTOS FOR
      SELECT ID_TRATAMIENTO, DESCRIPCION, FECHA_INICIO, FECHA_FIN, ID_PACIENTE,
             CREATION_DATE, CREATED_BY, LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_TRATAMIENTOS_TB;
END;
/


--FIDE_TRATAMIENTOS_PROCEDIMIENTOS_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_TRAT_PROCEDIMIENTOS_SP(
    LISTA_TRAT_PROCEDIMIENTOS OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_TRAT_PROCEDIMIENTOS FOR
      SELECT ID_TRATAMIENTO, ID_PROCEDIMIENTO
      FROM FIDE_TRATAMIENTOS_PROCEDIMIENTOS_TB;
END;
/

--FIDE_ESTADOS_CITAS_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_ESTADOS_CITAS_SP(
    LISTA_ESTADOS_CITAS OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_ESTADOS_CITAS FOR
      SELECT ID_ESTADO_CITA, NOMBRE_ESTADO, CREATION_DATE, CREATED_BY,
             LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_ESTADOS_CITAS_TB;
END;
/

--FIDE_CITAS_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_CITAS_SP(
    LISTA_CITAS OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_CITAS FOR
      SELECT ID_CITA, FECHA, HORA_CITA, ID_ESTADO_CITA, ID_DOCTOR, ID_PACIENTE,
             CREATION_DATE, CREATED_BY, LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_CITAS_TB;
END;
/

--FIDE_CITAS_TRATAMIENTOS_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_CITAS_TRATAMIENTOS_SP(
    LISTA_CITAS_TRATAMIENTOS OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_CITAS_TRATAMIENTOS FOR
      SELECT ID_CITA, ID_TRATAMIENTO
      FROM FIDE_CITAS_TRATAMIENTOS_TB;
END;
/

--FIDE_COSTOS_CITA_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_COSTOS_CITA_SP(
    LISTA_COSTOS_CITA OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_COSTOS_CITA FOR
      SELECT ID_COSTO, ID_CITA, MONTO, DESCRIPCION, CREATION_DATE, CREATED_BY,
             LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_COSTOS_CITA_TB;
END;
/

--FIDE_HISTORIAL_CITAS_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_HISTORIAL_CITAS_SP(
    LISTA_HISTORIAL_CITAS OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_HISTORIAL_CITAS FOR
      SELECT ID_HISTORIAL, ID_CITA, FECHA_CAMBIO, ID_ESTADO_ANTERIOR, 
             ID_ESTADO_NUEVO, OBSERVACIONES, ACTIVO
      FROM FIDE_HISTORIAL_CITAS_TB;
END;
/

--FIDE_MEDICAMENTOS_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_MEDICAMENTOS_SP(
    LISTA_MEDICAMENTOS OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_MEDICAMENTOS FOR
      SELECT ID_MEDICAMENTO, NOMBRE, DESCRIPCION, PRECIO, CREATION_DATE, CREATED_BY,
             LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_MEDICAMENTOS_TB;
END;
/

--FIDE_INVENTARIO_MEDICAMENTOS_TB
CREATE OR REPLACE PROCEDURE FIDE_LISTAR_INVENTARIO_MED_SP(
    LISTA_INVENTARIO_MED OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_INVENTARIO_MED FOR
      SELECT ID_INVENTARIO, ID_MEDICAMENTO, CANTIDAD, OBSERVACIONES,
             CREATION_DATE, CREATED_BY, LAST_UPDATE, LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_INVENTARIO_MEDICAMENTOS_TB;
END;
/

--FIDE_FACTURAS_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_FACTURAS_SP(
    LISTA_FACTURAS OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_FACTURAS FOR
      SELECT ID_FACTURA, NUMERO_FACTURA, FECHA_EMISION, FECHA_VENCIMIENTO, MONTO_TOTAL,
             ESTADO_PAGO, ID_PACIENTE, CREATION_DATE, CREATED_BY, LAST_UPDATE, 
             LAST_UPDATE_BY, ACCION, ACTIVO
      FROM FIDE_FACTURAS_TB;
END;
/

--FIDE_TRATAMIENTOS_MEDICAMENTOS_TB

CREATE OR REPLACE PROCEDURE FIDE_LISTAR_TRAT_MEDICAMENTOS_SP(
    LISTA_TRAT_MEDICAMENTOS OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN LISTA_TRAT_MEDICAMENTOS FOR
      SELECT ID_MEDICAMENTO, ID_TRATAMIENTO
      FROM FIDE_TRATAMIENTOS_MEDICAMENTOS_TB;
END;
/


