---Secuencia para ID_USUARIO
CREATE SEQUENCE ID_USUARIO_SEQ
START WITH 2000  
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_USUARIOS_TB_TRG
BEFORE INSERT ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
    :NEW.id_USUARIO := ID_USUARIO_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_USUARIOS_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_USUARIOS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_TRATAMIENTOS
CREATE SEQUENCE ID_TRATAMIENTO_SEQ
START WITH 1  
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_TRATAMIENTOS_TB_TRG
BEFORE INSERT ON FIDE_TRATAMIENTOS_TB
FOR EACH ROW
BEGIN
    :NEW.id_TRATAMIENTO := ID_TRATAMIENTO_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_TRATAMIENTOS_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_TRATAMIENTOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_TRATAMIENTOS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_TRATAMIENTOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_SUBESPECIALIDAD
CREATE SEQUENCE ID_SUBESPECIALIDAD_SEQ
START WITH 1000  
INCREMENT BY 1000
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_SUBESPECIALIDAD_TB_TRG
BEFORE INSERT ON FIDE_SUBESPECIALIDAD_TB
FOR EACH ROW
BEGIN
    :NEW.id_SUBESPECIALIDAD := ID_SUBESPECIALIDAD_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_SUBESPECIALIDAD_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_SUBESPECIALIDAD_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_SUBESPECIALIDAD_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_SUBESPECIALIDAD_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_SERVICIO
CREATE SEQUENCE ID_SERVICIO_SEQ
START WITH 1 
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_SERVICIO_TB_TRG
BEFORE INSERT ON FIDE_SERVICIO_TB
FOR EACH ROW
BEGIN
    :NEW.id_SERVICIO := ID_SERVICIO_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_SERVICIO_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_SERVICIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_SERVICIO_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_SERVICIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_PROCEDIMIENTO
CREATE SEQUENCE ID_PROCEDIMIENTO_SEQ
START WITH 10  
INCREMENT BY 5
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_PROCEDIMIENTOS_TB_TRG
BEFORE INSERT ON FIDE_PROCEDIMIENTOS_TB
FOR EACH ROW
BEGIN
    :NEW.id_PROCEDIMIENTO := ID_PROCEDIMIENTO_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_PROCEDIMIENTOS_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROCEDIMIENTOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_PROCEDIMIENTOS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROCEDIMIENTOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_ROL
CREATE SEQUENCE ID_ROL_SEQ
START WITH 40000  
INCREMENT BY 10
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_ROL_TB_TRG
BEFORE INSERT ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
    :NEW.id_ROL := ID_ROL_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_ROL_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_ROL_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_PAIS
CREATE SEQUENCE ID_PAIS_SEQ
START WITH 1 
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_PAISES_TB_TRG
BEFORE INSERT ON FIDE_PAISES_TB
FOR EACH ROW
BEGIN
    :NEW.id_PAIS := ID_PAIS_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_PAISES_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_PAISES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_PAISES_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PAISES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_PACIENTES
CREATE SEQUENCE ID_PACIENTE_SEQ
START WITH 1 
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_PACIENTES_TB_TRG
BEFORE INSERT ON FIDE_PACIENTES_TB
FOR EACH ROW
BEGIN
    :NEW.id_PACIENTE := ID_PACIENTE_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_PACIENTES_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_PACIENTES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_PACIENTES_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PACIENTES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_NOTIFICACIONES
CREATE SEQUENCE ID_NOTIFICACION_SEQ
START WITH 100000 
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_NOTIFICACIONES_TB_TRG
BEFORE INSERT ON FIDE_NOTIFICACIONES_TB
FOR EACH ROW
BEGIN
    :NEW.id_NOTIFICACION := ID_NOTIFICACION_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_NOTIFICACIONES_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_NOTIFICACIONES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_NOTIFICACIONES_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_NOTIFICACIONES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_MEDICAMENTOS
CREATE SEQUENCE ID_MEDICAMENTO_SEQ
START WITH 10
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_MEDICAMENTOS_TB_TRG
BEFORE INSERT ON FIDE_MEDICAMENTOS_TB
FOR EACH ROW
BEGIN
    :NEW.id_MEDICAMENTO := ID_MEDICAMENTO_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_MEDICAMENTOS_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_MEDICAMENTOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_MEDICAMENTOS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_MEDICAMENTOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_INVENTARIO
CREATE SEQUENCE ID_INVENTARIO_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_MEDICAMENTOS_TB_TRG
BEFORE INSERT ON FIDE_INVENTARIO_MEDICAMENTOS_TB
FOR EACH ROW
BEGIN
    :NEW.id_INVENTARIO := ID_INVENTARIO_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_MEDICAMENTOS_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_INVENTARIO_MEDICAMENTOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_MEDICAMENTOS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_INVENTARIO_MEDICAMENTOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_HISTORIAL
CREATE SEQUENCE ID_HISTORIAL_SEQ
START WITH 100
INCREMENT BY 2
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_HISTORIAL_CITAS_TB_TRG
BEFORE INSERT ON FIDE_HISTORIAL_CITAS_TB
FOR EACH ROW
BEGIN
    :NEW.id_HISTORIAL := ID_HISTORIAL_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
/* Solo si se crea el cambio en la tabla FIDE_HISTORIAL_CITAS_TB
CREATE OR REPLACE TRIGGER FIDE_HISTORIAL_CITAS_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_HISTORIAL_CITAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_HISTORIAL_CITAS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_HISTORIAL_CITAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/
*/

---Secuencia para ID_FACTURAS
CREATE SEQUENCE ID_FACTURA_SEQ
START WITH 10000
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_FACTURAS_TB_TRG
BEFORE INSERT ON FIDE_FACTURAS_TB
FOR EACH ROW
BEGIN
    :NEW.id_FACTURA := ID_FACTURA_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_FACTURAS_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_FACTURAS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_ESTADO_CITA
CREATE SEQUENCE ID_ESTADO_CITA_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_ESTADOS_CITAS_TB_TRG
BEFORE INSERT ON FIDE_ESTADOS_CITAS_TB
FOR EACH ROW
BEGIN
    :NEW.id_ESTADO_CITA := ID_ESTADO_CITA_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_ESTADOS_CITAS_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADOS_CITAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_ESTADOS_CITAS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADOS_CITAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_ESPECIALIDAD
CREATE SEQUENCE ID_ESPECIALIDAD_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_ESPECIALIDADES_TB_TRG
BEFORE INSERT ON FIDE_ESPECIALIDADES_TB
FOR EACH ROW
BEGIN
    :NEW.id_ESPECIALIDAD := ID_ESPECIALIDAD_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_ESPECIALIDADES_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESPECIALIDADES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_ESPECIALIDADES_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESPECIALIDADES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_DOCTOR
CREATE SEQUENCE ID_DOCTOR_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_DOCTORES_TB_TRG
BEFORE INSERT ON FIDE_DOCTORES_TB
FOR EACH ROW
BEGIN
    :NEW.id_DOCTOR := ID_DOCTOR_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_DOCTORES_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_DOCTORES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_DOCTORES_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DOCTORES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_DISTRITO
CREATE SEQUENCE ID_DISTRITO_SEQ
START WITH 10000
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_TB_TRG
BEFORE INSERT ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
    :NEW.id_DISTRITO := ID_DISTRITO_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_DISPONIBILIDAD
CREATE SEQUENCE ID_DISPONIBILIDAD_SEQ
START WITH 1
INCREMENT BY 10
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_DISPONIBILIDAD_TB_TRG
BEFORE INSERT ON FIDE_DISPONIBILIDAD_TB
FOR EACH ROW
BEGIN
    :NEW.id_DISPONIBILIDAD := ID_DISPONIBILIDAD_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_DISPONIBILIDAD_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISPONIBILIDAD_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_DISPONIBILIDAD_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISPONIBILIDAD_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_DIRECCION
CREATE SEQUENCE ID_DIRECCION_SEQ
START WITH 100
INCREMENT BY 100
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_DIRECCION_TB_TRG
BEFORE INSERT ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    :NEW.id_DIRECCION := ID_DIRECCION_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_DIRECCION_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_DIRECCION_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_COSTO
CREATE SEQUENCE ID_COSTO_SEQ
START WITH 1000
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_COSTOS_CITA_TB_TRG
BEFORE INSERT ON FIDE_COSTOS_CITA_TB
FOR EACH ROW
BEGIN
    :NEW.id_COSTO := ID_COSTO_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_COSTOS_CITA_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_COSTOS_CITA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_COSTOS_CITA_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_COSTOS_CITA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_CITA
CREATE SEQUENCE ID_CITA_SEQ
START WITH 10000
INCREMENT BY 100
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_CITAS_TB_TRG
BEFORE INSERT ON FIDE_CITAS_TB
FOR EACH ROW
BEGIN
    :NEW.id_CITA := ID_CITA_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_CITAS_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_CITAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_CITAS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CITAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/

---Secuencia para ID_CANTONES
CREATE SEQUENCE ID_CANTON_SEQ
START WITH 100
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER FIDE_CANTONES_TB_TRG
BEFORE INSERT ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
    :NEW.id_CANTON := ID_CANTON_SEQ.NEXTVAL;
    :NEW.ACTIVO := 1;
    
END;
/
CREATE OR REPLACE TRIGGER FIDE_CANTONES_TB_USER_DATE_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.Created_by := USER; 
        :NEW.Creation_date := SYSTIMESTAMP;
    END IF;
        :NEW.Last_update_by := USER;
        :NEW.Last_update := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER FIDE_CANTONES_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.accion := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.accion := 'UPDATE';
    END IF;
END;
/


