--1. Vista para Factura (Detalle de Facturación)

CREATE OR REPLACE VIEW V_FACTURA_DETALLE AS
SELECT 
    F.ID_FACTURA,
    F.NUMERO_FACTURA,
    F.FECHA_EMISION,
    F.MONTO_TOTAL,
    F.ESTADO_PAGO,
    C.ID_CITA,
    D.ID_DOCTOR,
    USR_DOC.NOMBRE || ' ' || USR_DOC.PRIMER_APELLIDO AS NOMBRE_DOCTOR,
    P.ID_PACIENTE,
    USR_PAC.NOMBRE || ' ' || USR_PAC.PRIMER_APELLIDO AS NOMBRE_PACIENTE,
    CC.MONTO AS COSTO_CITA,
    CC.DESCRIPCION AS DESCRIPCION_COSTO
FROM 
    FIDE_FACTURAS_TB F
JOIN 
    FIDE_PACIENTES_TB P ON F.ID_PACIENTE = P.ID_PACIENTE
JOIN 
    FIDE_USUARIOS_TB USR_PAC ON P.ID_USUARIO = USR_PAC.ID_USUARIO
JOIN 
    FIDE_CITAS_TB C ON C.ID_PACIENTE = P.ID_PACIENTE
JOIN 
    FIDE_DOCTORES_TB D ON C.ID_DOCTOR = D.ID_DOCTOR
JOIN 
    FIDE_USUARIOS_TB USR_DOC ON D.ID_USUARIO = USR_DOC.ID_USUARIO
LEFT JOIN 
    FIDE_COSTOS_CITA_TB CC ON CC.ID_CITA = C.ID_CITA;
    
    

--2. Vista para Citas con Costos y Doctores

CREATE OR REPLACE VIEW V_CITAS_CON_COSTOS AS
SELECT 
    C.ID_CITA,
    C.FECHA,
    C.HORA_CITA,
    EC.NOMBRE_ESTADO AS ESTADO_CITA,
    D.ID_DOCTOR,
    USR_DOC.NOMBRE || ' ' || USR_DOC.PRIMER_APELLIDO AS NOMBRE_DOCTOR,
    P.ID_PACIENTE,
    USR_PAC.NOMBRE || ' ' || USR_PAC.PRIMER_APELLIDO AS NOMBRE_PACIENTE,
    CC.MONTO AS COSTO,
    CC.DESCRIPCION AS DETALLE_COSTO
FROM 
    FIDE_CITAS_TB C
JOIN 
    FIDE_ESTADOS_CITAS_TB EC ON C.ID_ESTADO_CITA = EC.ID_ESTADO_CITA
JOIN 
    FIDE_DOCTORES_TB D ON C.ID_DOCTOR = D.ID_DOCTOR
JOIN 
    FIDE_USUARIOS_TB USR_DOC ON D.ID_USUARIO = USR_DOC.ID_USUARIO
JOIN 
    FIDE_PACIENTES_TB P ON C.ID_PACIENTE = P.ID_PACIENTE
JOIN 
    FIDE_USUARIOS_TB USR_PAC ON P.ID_USUARIO = USR_PAC.ID_USUARIO
LEFT JOIN 
    FIDE_COSTOS_CITA_TB CC ON CC.ID_CITA = C.ID_CITA;
    
    
    
--3. Vista Resumen de Costos por Doctor


CREATE OR REPLACE VIEW V_RESUMEN_COSTOS_DOCTOR AS
SELECT 
    D.ID_DOCTOR,
    USR_DOC.NOMBRE || ' ' || USR_DOC.PRIMER_APELLIDO AS NOMBRE_DOCTOR,
    COUNT(C.ID_CITA) AS TOTAL_CITAS,
    NVL(SUM(CC.MONTO), 0) AS INGRESOS_TOTALES
FROM 
    FIDE_DOCTORES_TB D
JOIN 
    FIDE_USUARIOS_TB USR_DOC ON D.ID_USUARIO = USR_DOC.ID_USUARIO
LEFT JOIN 
    FIDE_CITAS_TB C ON D.ID_DOCTOR = C.ID_DOCTOR
LEFT JOIN 
    FIDE_COSTOS_CITA_TB CC ON CC.ID_CITA = C.ID_CITA
GROUP BY 
    D.ID_DOCTOR, USR_DOC.NOMBRE, USR_DOC.PRIMER_APELLIDO;
    
    
    
--4. Vista Detalle de Facturación con Citas 

CREATE OR REPLACE VIEW V_DETALLE_FACTURA_CITAS AS
SELECT 
    F.ID_FACTURA,
    C.ID_CITA,
    C.FECHA AS FECHA_CITA,
    D.ID_DOCTOR,
    USR_DOC.NOMBRE || ' ' || USR_DOC.PRIMER_APELLIDO AS DOCTOR,
    CC.MONTO AS COSTO_CITA,
    F.MONTO_TOTAL AS MONTO_FACTURA
FROM 
    FIDE_FACTURAS_TB F
JOIN 
    FIDE_PACIENTES_TB P ON F.ID_PACIENTE = P.ID_PACIENTE
JOIN 
    FIDE_CITAS_TB C ON C.ID_PACIENTE = P.ID_PACIENTE
JOIN 
    FIDE_DOCTORES_TB D ON C.ID_DOCTOR = D.ID_DOCTOR
JOIN 
    FIDE_USUARIOS_TB USR_DOC ON D.ID_USUARIO = USR_DOC.ID_USUARIO
LEFT JOIN 
    FIDE_COSTOS_CITA_TB CC ON CC.ID_CITA = C.ID_CITA
WHERE 
    C.FECHA BETWEEN F.FECHA_EMISION AND NVL(F.FECHA_VENCIMIENTO, SYSDATE);
    
    
    
--5. Pacientes con Tratamientos Activos

CREATE OR REPLACE VIEW V_PACIENTES_TRATAMIENTOS_ACTIVOS AS
SELECT 
    P.ID_PACIENTE,
    U.NOMBRE || ' ' || U.PRIMER_APELLIDO AS NOMBRE_PACIENTE,
    T.ID_TRATAMIENTO,
    T.DESCRIPCION AS TRATAMIENTO,
    T.FECHA_INICIO,
    T.FECHA_FIN
FROM 
    FIDE_PACIENTES_TB P
JOIN 
    FIDE_USUARIOS_TB U ON P.ID_USUARIO = U.ID_USUARIO
JOIN 
    FIDE_TRATAMIENTOS_TB T ON P.ID_PACIENTE = T.ID_PACIENTE
WHERE 
    T.ACTIVO = 1 
    AND (T.FECHA_FIN IS NULL OR T.FECHA_FIN >= SYSDATE);
    
    
--6. Doctores por Especialidad

CREATE OR REPLACE VIEW V_DOCTORES_ESPECIALIDAD AS
SELECT 
    E.ID_ESPECIALIDAD,
    E.NOMBRE AS ESPECIALIDAD,
    D.ID_DOCTOR,
    U.NOMBRE || ' ' || U.PRIMER_APELLIDO AS NOMBRE_DOCTOR,
    D.NUMEROL_ICENCIA AS LICENCIA
FROM 
    FIDE_ESPECIALIDADES_TB E
JOIN 
    FIDE_DOCTORES_ESPECIALIDADES_TB DE ON E.ID_ESPECIALIDAD = DE.ID_ESPECIALIDAD
JOIN 
    FIDE_DOCTORES_TB D ON DE.ID_DOCTOR = D.ID_DOCTOR
JOIN 
    FIDE_USUARIOS_TB U ON D.ID_USUARIO = U.ID_USUARIO
WHERE 
    D.ACTIVO = 1;
    
    
--7. Citas Pendientes

CREATE OR REPLACE VIEW V_CITAS_PENDIENTES AS
SELECT 
    C.ID_CITA,
    C.FECHA,
    C.HORA_CITA,
    EC.NOMBRE_ESTADO AS ESTADO,
    P.ID_PACIENTE,
    U_PAC.NOMBRE || ' ' || U_PAC.PRIMER_APELLIDO AS PACIENTE,
    D.ID_DOCTOR,
    U_DOC.NOMBRE || ' ' || U_DOC.PRIMER_APELLIDO AS DOCTOR
FROM 
    FIDE_CITAS_TB C
JOIN 
    FIDE_ESTADOS_CITAS_TB EC ON C.ID_ESTADO_CITA = EC.ID_ESTADO_CITA
JOIN 
    FIDE_PACIENTES_TB P ON C.ID_PACIENTE = P.ID_PACIENTE
JOIN 
    FIDE_USUARIOS_TB U_PAC ON P.ID_USUARIO = U_PAC.ID_USUARIO
JOIN 
    FIDE_DOCTORES_TB D ON C.ID_DOCTOR = D.ID_DOCTOR
JOIN 
    FIDE_USUARIOS_TB U_DOC ON D.ID_USUARIO = U_DOC.ID_USUARIO
WHERE 
    EC.NOMBRE_ESTADO = 'PENDIENTE' -- Ajusta según tus valores reales
    AND C.ACTIVO = 1;
    
    
--8.  Medicamentos en Inventario

CREATE OR REPLACE VIEW V_MEDICAMENTOS_BAJO_STOCK AS
SELECT 
    M.ID_MEDICAMENTO,
    M.NOMBRE AS MEDICAMENTO,
    I.CANTIDAD,
    M.PRECIO,
    CASE 
        WHEN I.CANTIDAD < 10 THEN 'CRÍTICO'
        WHEN I.CANTIDAD BETWEEN 10 AND 20 THEN 'BAJO'
        ELSE 'SUFICIENTE'
    END AS ESTADO_STOCK
FROM 
    FIDE_MEDICAMENTOS_TB M
JOIN 
    FIDE_INVENTARIO_MEDICAMENTOS_TB I ON M.ID_MEDICAMENTO = I.ID_MEDICAMENTO
WHERE 
    I.CANTIDAD < 20 -- Umbral ajustable
    AND I.ACTIVO = 1;
    
    
    
--9.Historial de Cambios de Estado en Citas

CREATE OR REPLACE VIEW V_HISTORIAL_ESTADOS_CITAS AS
SELECT 
    HC.ID_HISTORIAL,
    C.ID_CITA,
    EC_ANT.NOMBRE_ESTADO AS ESTADO_ANTERIOR,
    EC_NUEVO.NOMBRE_ESTADO AS ESTADO_NUEVO,
    HC.FECHA_CAMBIO,
    HC.OBSERVACIONES
FROM 
    FIDE_HISTORIAL_CITAS_TB HC
JOIN 
    FIDE_CITAS_TB C ON HC.ID_CITA = C.ID_CITA
LEFT JOIN 
    FIDE_ESTADOS_CITAS_TB EC_ANT ON HC.ID_ESTADO_ANTERIOR = EC_ANT.ID_ESTADO_CITA
LEFT JOIN 
    FIDE_ESTADOS_CITAS_TB EC_NUEVO ON HC.ID_ESTADO_NUEVO = EC_NUEVO.ID_ESTADO_CITA
ORDER BY 
    HC.FECHA_CAMBIO DESC;
    
    
--10.Disponibilidad de Doctores por Día

CREATE OR REPLACE VIEW V_DISPONIBILIDAD_DOCTORES AS
SELECT 
    D.ID_DOCTOR,
    U.NOMBRE || ' ' || U.PRIMER_APELLIDO AS DOCTOR,
    DIS.DIA,
    TO_CHAR(DIS.HORA_INICIO, 'HH24:MI') AS HORA_INICIO,
    TO_CHAR(DIS.HORA_FIN, 'HH24:MI') AS HORA_FIN
FROM 
    FIDE_DISPONIBILIDAD_TB DIS
JOIN 
    FIDE_DOCTORES_TB D ON DIS.ID_DOCTOR = D.ID_DOCTOR
JOIN 
    FIDE_USUARIOS_TB U ON D.ID_USUARIO = U.ID_USUARIO
WHERE 
    DIS.ACTIVO = 1
ORDER BY 
    D.ID_DOCTOR, DIS.DIA;
    
    
    
--11.   Procedimientos Más Comunes en Tratamientos

CREATE OR REPLACE VIEW V_PROCEDIMIENTOS_COMUNES AS
SELECT 
    PR.ID_PROCEDIMIENTO,
    PR.NOMBRE_PROCEDIMIENTO,
    PR.TIPO_PROCEDIMIENTO,
    COUNT(TP.ID_TRATAMIENTO) AS TOTAL_USOS
FROM 
    FIDE_PROCEDIMIENTOS_TB PR
JOIN 
    FIDE_TRATAMIENTOS_PROCEDIMIENTOS_TB TP ON PR.ID_PROCEDIMIENTO = TP.ID_PROCEDIMIENTO
GROUP BY 
    PR.ID_PROCEDIMIENTO, PR.NOMBRE_PROCEDIMIENTO, PR.TIPO_PROCEDIMIENTO
ORDER BY 
    TOTAL_USOS DESC;
    
    
--12.  Resumen de Pagos por Paciente

CREATE OR REPLACE VIEW V_RESUMEN_PAGOS_PACIENTE AS
SELECT 
    P.ID_PACIENTE,
    U.NOMBRE || ' ' || U.PRIMER_APELLIDO AS PACIENTE,
    COUNT(F.ID_FACTURA) AS TOTAL_FACTURAS,
    SUM(F.MONTO_TOTAL) AS MONTO_TOTAL,
    MIN(F.FECHA_EMISION) AS PRIMER_PAGO,
    MAX(F.FECHA_EMISION) AS ULTIMO_PAGO
FROM 
    FIDE_PACIENTES_TB P
JOIN 
    FIDE_USUARIOS_TB U ON P.ID_USUARIO = U.ID_USUARIO
LEFT JOIN 
    FIDE_FACTURAS_TB F ON P.ID_PACIENTE = F.ID_PACIENTE
GROUP BY 
    P.ID_PACIENTE, U.NOMBRE, U.PRIMER_APELLIDO;
    
    
--13. Subespecialidades por Especialidad

CREATE OR REPLACE VIEW V_SUBESPECIALIDADES_DETALLE AS
SELECT 
    S.ID_SUBESPECIALIDAD,
    S.NOMBRE AS SUBESPECIALIDAD,
    E.ID_ESPECIALIDAD,
    E.NOMBRE AS ESPECIALIDAD_PADRE,
    S.DESCRIPCION
FROM 
    FIDE_SUBESPECIALIDAD_TB S
JOIN 
    FIDE_ESPECIALIDADES_TB E ON S.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD
WHERE 
    S.ACTIVO = 1;
    
    
--14.  Citas con Tratamientos y Medicamentos

CREATE OR REPLACE VIEW V_CITAS_TRATAMIENTOS_MEDICAMENTOS AS
SELECT 
    C.ID_CITA,
    CT.ID_TRATAMIENTO,
    T.DESCRIPCION AS TRATAMIENTO,
    TM.ID_MEDICAMENTO,
    M.NOMBRE AS MEDICAMENTO,
    M.PRECIO AS PRECIO_UNITARIO
FROM 
    FIDE_CITAS_TB C
JOIN 
    FIDE_CITAS_TRATAMIENTOS_TB CT ON C.ID_CITA = CT.ID_CITA
JOIN 
    FIDE_TRATAMIENTOS_TB T ON CT.ID_TRATAMIENTO = T.ID_TRATAMIENTO
LEFT JOIN 
    FIDE_TRATAMIENTOS_MEDICAMENTOS_TB TM ON T.ID_TRATAMIENTO = TM.ID_TRATAMIENTO
LEFT JOIN 
    FIDE_MEDICAMENTOS_TB M ON TM.ID_MEDICAMENTO = M.ID_MEDICAMENTO
WHERE 
    C.ACTIVO = 1;
    
--15. Doctores con Mayor Número de Citas Atendidas


CREATE OR REPLACE VIEW V_DOCTORES_TOP_CITAS AS
SELECT 
    D.ID_DOCTOR,
    U.NOMBRE || ' ' || U.PRIMER_APELLIDO AS DOCTOR,
    E.NOMBRE AS ESPECIALIDAD,
    COUNT(C.ID_CITA) AS TOTAL_CITAS_ATENDIDAS,
    ROUND(COUNT(C.ID_CITA) * 100.0 / (SELECT COUNT(*) FROM FIDE_CITAS_TB), 2) AS PORCENTAJE
FROM 
    FIDE_DOCTORES_TB D
JOIN 
    FIDE_USUARIOS_TB U ON D.ID_USUARIO = U.ID_USUARIO
JOIN 
    FIDE_CITAS_TB C ON D.ID_DOCTOR = C.ID_DOCTOR
JOIN 
    FIDE_DOCTORES_ESPECIALIDADES_TB DE ON D.ID_DOCTOR = DE.ID_DOCTOR
JOIN 
    FIDE_ESPECIALIDADES_TB E ON DE.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD
WHERE 
    C.ID_ESTADO_CITA = (SELECT ID_ESTADO_CITA FROM FIDE_ESTADOS_CITAS_TB WHERE NOMBRE_ESTADO = 'COMPLETADA') -- Ajustar según valores reales
GROUP BY 
    D.ID_DOCTOR, U.NOMBRE, U.PRIMER_APELLIDO, E.NOMBRE
ORDER BY 
    TOTAL_CITAS_ATENDIDAS DESC;
    
    
--16.  Pacientes con Tratamientos por Vencer 


CREATE OR REPLACE VIEW V_TRATAMIENTOS_POR_VENCER AS
SELECT 
    P.ID_PACIENTE,
    U.NOMBRE || ' ' || U.PRIMER_APELLIDO AS PACIENTE,
    T.ID_TRATAMIENTO,
    T.DESCRIPCION AS TRATAMIENTO,
    T.FECHA_FIN,
    TRUNC(T.FECHA_FIN - SYSDATE) AS DIAS_RESTANTES
FROM 
    FIDE_PACIENTES_TB P
JOIN 
    FIDE_USUARIOS_TB U ON P.ID_USUARIO = U.ID_USUARIO
JOIN 
    FIDE_TRATAMIENTOS_TB T ON P.ID_PACIENTE = T.ID_PACIENTE
WHERE 
    T.FECHA_FIN BETWEEN SYSDATE AND SYSDATE + 30
    AND T.ACTIVO = 1;
    
    
--17. Disponibilidad de Consultorios por Especialidad

CREATE OR REPLACE VIEW V_CONSULTORIOS_ESPECIALIDAD AS
SELECT 
    E.ID_ESPECIALIDAD,
    E.NOMBRE AS ESPECIALIDAD,
    D.ID_DOCTOR,
    U.NOMBRE || ' ' || U.PRIMER_APELLIDO AS DOCTOR,
    DIR.ID_DIRECCION,
    PA.NOMBRE AS PAIS,
    CA.NOMBRE AS CANTON,
    DI.NOMBRE AS DISTRITO
FROM 
    FIDE_ESPECIALIDADES_TB E
JOIN 
    FIDE_DOCTORES_ESPECIALIDADES_TB DE ON E.ID_ESPECIALIDAD = DE.ID_ESPECIALIDAD
JOIN 
    FIDE_DOCTORES_TB D ON DE.ID_DOCTOR = D.ID_DOCTOR
JOIN 
    FIDE_USUARIOS_TB U ON D.ID_USUARIO = U.ID_USUARIO
JOIN 
    FIDE_DIRECCION_TB DIR ON D.ID_DIRECCION = DIR.ID_DIRECCION
JOIN 
    FIDE_PAISES_TB PA ON DIR.ID_PAIS = PA.ID_PAIS
JOIN 
    FIDE_CANTONES_TB CA ON DIR.ID_CANTON = CA.ID_CANTON
JOIN 
    FIDE_DISTRITOS_TB DI ON DIR.ID_DISTRITO = DI.ID_DISTRITO
WHERE 
    D.ACTIVO = 1;
    
--18.  Eficiencia en Uso de Medicamentos

CREATE OR REPLACE VIEW V_EFICIENCIA_MEDICAMENTOS AS
SELECT 
    M.ID_MEDICAMENTO,
    M.NOMBRE AS MEDICAMENTO,
    COUNT(DISTINCT TM.ID_TRATAMIENTO) AS TOTAL_TRATAMIENTOS,
    COUNT(DISTINCT P.ID_PACIENTE) AS PACIENTES_ATENDIDOS,
    SUM(M.PRECIO) AS INGRESOS_GENERADOS,
    ROUND(SUM(M.PRECIO) / NULLIF(COUNT(DISTINCT P.ID_PACIENTE), 0), 2) AS COSTO_POR_PACIENTE
FROM 
    FIDE_MEDICAMENTOS_TB M
JOIN 
    FIDE_TRATAMIENTOS_MEDICAMENTOS_TB TM ON M.ID_MEDICAMENTO = TM.ID_MEDICAMENTO
JOIN 
    FIDE_TRATAMIENTOS_TB T ON TM.ID_TRATAMIENTO = T.ID_TRATAMIENTO
JOIN 
    FIDE_PACIENTES_TB P ON T.ID_PACIENTE = P.ID_PACIENTE
GROUP BY 
    M.ID_MEDICAMENTO, M.NOMBRE;
    /


